### ISSUE TITLE
sort-tab 无法在 emacs daemon-mode 下工作。

### ISSUE THREAD

**Issue by zw963** [manateelazycat/sort-tab#10]
如果首先启动 emacs --daemon, 然后再使用 emacsclient 连接上来后，看不到 sort-tab.

但是正常直接启动 emacs 却是可以的。

我的配置：

```cl
(require 'sort-tab)

(sort-tab-mode t)
```

我可以在以上最小配置下重现。

顺便提一句: awesome-tab 是可以在 daemon 下工作的。

谢谢

**Comment by manateelazycat** [comment]
发PR哈， 我不用的东西， 我没有太多时间研究

**Comment by zw963** [comment]
> 发PR哈， 我不用的东西， 我没有太多时间研究

我也不知道怎么回事儿哇。awesome-tab 可以，sort-tab 不可以。

不过我想了个办法解决掉了, 代码大概这个样子。

```elisp
(defun initialize-frame-delay (&optional frame)
  (run-with-idle-timer 0 nil 'sort-tab-turn-on))

(if (and (fboundp 'daemonp) (daemonp))
    (add-hook 'after-make-frame-functions 'initialize-frame-delay t)
  )
```

我不认为这是解决问题的方式，因为 awesome-tab 里面没看到类似代码。

**Comment by manateelazycat** [comment]
awesome-tab 和 sort-tab 的原理不一样啊。

awesome-tab 是buffer显示才显示， sort-tab 是独立的窗口， 你 daemon 启动它肯定没法启动啊。

**Comment by zw963** [comment]
那你考虑合并上面代码吗？ 确定在  daemon 模式下是工作的，我可以建个 PR.

**Comment by manateelazycat** [comment]
> 那你考虑合并上面代码吗？ 确定在 daemon 模式下是工作的，我可以建个 PR.

可以啊， 应该没有问题啊， 可以合并。
