### ISSUE TITLE
当全局开启 company-mode 的时候， sort-tab 造成 completion 失败。

### ISSUE THREAD

**Issue by zw963** [manateelazycat/sort-tab#13]
我是全局开启 company-mode 的。

```
(global-company-mode 1)
```

然后当完成出现时，得到下面的错误。

Company: backend (company-dabbrev-code company-gtags company-etags company-keywords) error "Wrong number of arguments: ((t) nil (let ((current-buffer (window-buffer))) (cond ((sort-tab-is-normal-buffer-p current-buffer) (let* ((current-tab-start-column 0) (current-tab-end-column 0) (tab-window (get-buffer-window (sort-tab-get-buffer))) found-current-tab tab) (save-current-buffer (set-buffer (sort-tab-get-buffer)) (erase-buffer) (if (not (string-prefix-p "sort-tab-" (prin1-to-string last-command))) (progn (setq sort-tab-visible-buffers (sort-tab-get-buffer-list)))) (let ((--dolist-tail-- sort-tab-visible-buffers)) (while --dolist-tail-- (let ((buf (car --dolist-tail--))) (setq tab (sort-tab-get-tab-name buf current-buffer)) (insert tab) (insert sort-tab-propertized-separator) (if found-current-tab nil (if (eq buf current-buffer) (progn (setq found-current-tab t) (setq current-tab-start-column current-tab-end-column))) (setq current-tab-end-column (+ current-tab-end-column (length tab) (length sort-tab-separator)))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (if tab-window (progn (let ((save-selected-window--state (internal--before-with-selected-window tab-window))) (save-current-buffer (unwind-protect (progn (select-window (car save-selected-window--state) 'norecord) (cond ((> current-tab-end-column (+ (window-hscroll) (window-width))) (scroll-left (+ (- current-tab-end-column (window-hscroll) (window-width)) (/ (window-width) 2)))) ((< current-tab-start-column (window-hscroll)) (set-window-hscroll tab-window current-tab-start-column)))) (internal--after-with-selected-window save-selected-window--state)))))) (if (eq sort-tab-align 'center) (progn (goto-char (point-min)) (insert sort-tab-propertized-separator) (let* ((width (window-width (get-buffer-window))) (content-length (length (buffer-string))) (padding (max 0 (/ (- width content-length) 2)))) (goto-char (point-min)) (insert (make-string padding 32))))) (setq sort-tab-
last-active-buffer (current-buffer))))) ((sort-tab-is-hidden-buffer-p current-buffer) (save-current-buffer (set-buffer (sort-tab-get-buffer)) (erase-buffer) (insert (sort-tab-get-tab-name current-buffer current-buffer)) (insert sort-tab-propertized-separator) (if (eq sort-tab-align 'center) (progn (goto-char (point-min)) (insert sort-tab-propertized-separator) (let* ((width (window-width (get-buffer-window))) (content-length (length (buffer-string))) (padding (max 0 (/ (- width content-length) 2)))) (goto-char (point-min)) (insert (make-string padding 32))))) (setq sort-tab-last-active-buffer (current-buffer)))) ((string-equal sort-tab-buffer-name (buffer-name current-buffer)) (save-current-buffer (set-buffer (sort-tab-get-buffer)) (erase-buffer) (if (eq sort-tab-align 'center) (progn (goto-char (point-min)) (insert sort-tab-propertized-separator) (let* ((width (window-width (get-buffer-window))) (content-length (length (buffer-string))) (padding (max 0 (/ (- width content-length) 2)))) (goto-char (point-min)) (insert (make-string padding 32))))) (setq sort-tab-last-active-buffer (current-buffer))))))), 1" with args (candidates String)

是不是因为 sort-tab 那个独立窗口开启了 company-mode 缘故？

查了下 company 文档，它是支持在某些条件下不开启的。

[(setq company-global-modes '(not org-mode))](https://stackoverflow.com/a/34660219/749774)

但是我不知道该如何在那个 sort-tab 独立窗口关闭它。

当然也可能是其他原因，我甚至没有开启 sort-tab-mode, 只是 require 之后，就有这个错误。

谢谢。

**Comment by manateelazycat** [comment]
因为 sort-tab 本质是一个 dedicated window, 如果其他模式设计时没有排除这种窗口就很容易出问题。

我一般是 https://github.com/emacs-eaf/eaf-git/blob/28678aeb5909934bc9b92279e980491102e0c34e/eaf-git.el#L359 解决的。

本质是 sort-tab 有独特的设计， 是别的插件不认识 sort-tab 导致的错误， sort-tab 本身没法通过改变去做兼容性代码。

**Comment by zw963** [comment]
> 因为 sort-tab 本质是一个 dedicated window, 如果其他插件设计时没有排除这种窗口就很容易出问题。
> 
> 我一般是 https://github.com/emacs-eaf/eaf-git/blob/28678aeb5909934bc9b92279e980491102e0c34e/eaf-git.el#L359 解决的。
> 
> 本质是 sort-tab 有独特的设计， 是别的插件不认识 sort-tab 导致的错误， sort-tab 本身没法通过改变去做兼容性代码。

不太明白你是如何解决的, 我加了下面的代码，还是报错？

```el
(add-hook 'company-mode-hook
          (lambda ()
            (cl-remove-if #'window-dedicated-p (window-list)))
```

**Comment by manateelazycat** [comment]
我不用company

**Comment by zw963** [comment]
> 我不用company

这个问题无法重现了，所以，最后你还是修了 ...
