### ISSUE TITLE
sort-tab在打开ibuffer以后消失了。

### ISSUE THREAD

**Issue by kapmix** [manateelazycat/sort-tab#23]
如题。
退出ibuffer以后，得重新进入sort-tab-mode才能出现tab。

version:
Mac, GNU Emacs 30.0.91

**Comment by manateelazycat** [comment]
我测试了一下， 不会出现这个问题， 请 emacs -Q 对比测试一下

**Comment by kapmix** [comment]
找到原因了，我写了个函数
`(defun my-close-current-tab ()
	"Close current buffer and delete other windows, so make the current window as the only."
	(interactive)
	(sort-tab-close-current-tab)
	(delete-other-windows)
	)`
这个函数：有时候会分栏显示一个调试信息等的窗口，关闭它，并且不分栏了。执行这个函数就乱了。
