### ISSUE TITLE
Problematic focus when using company

### ISSUE THREAD

**Issue by shrubbroom** [manateelazycat/sort-tab#3]
I am using emacs, whose version is mac-port 27.2.  When `company-mode` is turned on and the tooltip pops up right after the first char is inserted, sort-tab will focus on wrong buffer. 
<img width="912" alt="截屏2022-02-10 下午6 47 37" src="https://user-images.githubusercontent.com/49093544/153391695-f33c6808-e79d-4cc1-b0a3-44f11e4fa73a.png">

The sort-tab should focus on the `tmp.el`, however, it focuses on the `tmp.lua` as I typed the firs char. The minimal configuration to reproduce the behavior is shown as follow.
```emacs-lisp
(package-initialize)
(add-to-list 'load-path
             (concat user-emacs-directory "site-packages/sort-tab"))
(require 'sort-tab)
(sort-tab-mode +1)
(require 'company)
(setq company-idle-delay 0
      company-minimum-prefix-length 1)
(global-company-mode)

```
This behavior is not harming the functionality since sort-tab will focus correct buffer as more char is inserted. However, it may be annoying as the focused buffer changes rapidly. Modifying the following line may help. 
From
```elisp
LINE 280:sort-tab.el:   (let ((current-buffer (current-buffer)))
```
to
```elisp
LINE 280:sort-tab.el:   (let ((current-buffer (window-buffer)))
```
I have no idea if this would break other functionalities.

BR

**Comment by manateelazycat** [comment]
I can't reproduce your problem, can you test with "emacs -Q" ?

Thanks

**Comment by shrubbroom** [comment]
I can reproduce the problem with `emacs -Q`. After the emacs is started, I eval
``` elisp
(package-initialize)
(require 'sort-tab)
(sort-tab-mode +1)
(require 'company)
(setq company-idle-delay 0
      company-minimum-prefix-length 1)
(global-company-mode)
```
and create two new files. One `tmp.c` is just empty, the other one is `tmp.el`. When one char is inserted and company is active, the wrong buffer would be focused.
<img width="912" alt="截屏2022-02-11 下午6 22 15" src="https://user-images.githubusercontent.com/49093544/153575102-84b3581c-f9d7-470f-8929-e7c6e0660a64.png">
The sort-tab should focus on `tmp.el` rather than `tmp.c` here.

The version of my company is `company-20220110.2248`, the sort-tab version is HEAD. I have tried to reinstall company, but it doesn't help.

BR

**Comment by manateelazycat** [comment]
Please try newest version.
