### ISSUE TITLE
Feature request: make separator customizable

### ISSUE THREAD

**Issue by shrubbroom** [manateelazycat/sort-tab#5]
The separator is `"|"` by default.   However, I prefer to use no separator, which makes the tab-bar look nicer under my theme
![image](https://user-images.githubusercontent.com/49093544/162434182-da431e8d-d9b1-44c7-b060-529d423f718c.png)
Maybe it will be better to make the separator a `defcustom` rather than hardcoding it in the source code?

BR

**Comment by manateelazycat** [comment]
Done, I suggestion you use sort-tab.el with my another plugin awesome-tray.el ;)
